#ifndef AUDIO_TRACKS_H
#define AUDIO_TRACKS_H
enum AudioTracks {
    TRACK_DJ = 0,
    TRACK_POWER_UP = 1,
    TRACK_LEFT_SPEAKER_TEST = 2,
    TRACK_RIGHT_SPEAKER_TEST = 3,
    TRACK_POWERED_ON = 4,
    TRACK_CHARGING = 5,
    TRACK_POWER_OFF = 6,
    TRACK_LOW_BATTERY = 7,
    TRACK_FRONT_SENSOR_NOT_LEVEL = 8,
    TRACK_TILT = 10,
    TRACK_ERROR_GENERIC = 50,
    TRACK_ERROR_LET_GO_POWER = 51,
    TRACK_DROP_FRONT = 100,
    TRACK_OBJECT_FRONT = 101,
    TRACK_DROP_RIGHT = 102,
    TRACK_OBJECT_RIGHT = 103,
    TRACK_DROP_LEFT = 104,
    TRACK_OBJECT_LEFT = 105,
    TRACK_CALM_DROP_LEFT = 106,
    TRACK_CALM_DROP_RIGHT = 107,
    TRACK_CURBCUT_FRONT = 108,
};
const uint32_t TRACK_CHARGING_TIME = 1750;
const uint32_t TRACK_POWER_OFF_TIME = 3000;
const uint32_t TRACK_ERROR_LET_GO_POWER_TIME = 5000;
const uint32_t TRACK_LOW_BATTERY_TIME = 5000;
const uint32_t TRACK_POWER_UP_TIME = 4000;
const uint32_t TRACK_TILT_TIME = 13000;

#endif // AUDIO_TRACKS_H
