#ifndef AUDIO_TRACKS_H
#define AUDIO_TRACKS_H
enum AudioTracks {
    TRACK_DJ = 0,
    TRACK_POWER_UP = 1,
    TRACK_LEFT_SPEAKER_TEST = 2,
    TRACK_RIGHT_SPEAKER_TEST = 3,
    TRACK_POWERED_ON = 4,
    TRACK_ERROR_GENERIC = 50,
    TRACK_DROP_FRONT=100,
    TRACK_OBJECT_FRONT=101,
    TRACK_DROP_RIGHT=102,
    TRACK_OBJECT_RIGHT=103,
    TRACK_DROP_LEFT=104,
    TRACK_OBJECT_LEFT=105,
    TRACK_CALM_DROP_LEFT=106,
    TRACK_CALM_DROP_RIGHT=107,
    TRACK_CURBCUT_FRONT=108,
};

#endif // AUDIO_TRACKS_H
